# Generated by Django 4.1.4 on 2023-08-03 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='user',
            new_name='userr',
        ),
    ]
