# Generated by Django 4.1.4 on 2023-07-29 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0005_product_image_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
