# Generated by Django 4.1.4 on 2023-08-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0010_remove_product_image_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
