# Generated by Django 4.1.4 on 2023-08-04 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0015_remove_product_description_remove_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productsize', to='adminside.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.IntegerField(),
        ),
    ]
