# Generated by Django 4.1.4 on 2023-09-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0017_alter_product_brand_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='crop_height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productimage',
            name='crop_width',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productimage',
            name='crop_x',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productimage',
            name='crop_y',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
