# Generated by Django 4.1.4 on 2023-09-06 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coin_discount',
        ),
    ]
