# Generated by Django 4.1.4 on 2023-09-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_cart_coin_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coin_discount',
            field=models.IntegerField(default=0),
        ),
    ]
