# Generated by Django 4.1.4 on 2023-08-24 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product_size',
        ),
    ]
