# Generated by Django 4.1.4 on 2023-08-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_orderreturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='returnpolicy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='returnstatus',
            field=models.BooleanField(default=False),
        ),
    ]
