# Generated by Django 4.1.4 on 2023-09-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_wallet_user_alter_wallethistory_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
