# Generated by Django 4.1.4 on 2023-08-12 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_total_amount_orderitem_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='total_amount',
            new_name='total_itemprice',
        ),
    ]
